[package]
name = "mdbook_summary_fork4ls"
version = "0.5.2"
description = "Summary parser for mdBook"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "mdbook_summary"

[dependencies]
anyhow.workspace = true
mdbook-core.workspace = true
memchr.workspace = true
pulldown-cmark.workspace = true
serde.workspace = true
tracing.workspace = true

[lints]
workspace = true
